# apiVersion: v1
# kind: Service
# metadata:
#   name: synchro-service-internal
# spec:
#   clusterIP: None # headless service, allows us to access the pod ips and not just cluster ip.
#   selector:
#     app: synchro-app
#   ports:
#     - protocol: TCP
#       port: 80
#       targetPort: 8080
# ---
apiVersion: v1
kind: Service
metadata:
  name: synchro-service-external
spec:
  selector:
    app: "synchro-app"
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: NodePort # NodePort for external access